### ISSUE TITLE
Path params not working

### ISSUE THREAD

**Issue by dwoske** [coopernurse/caddy-awslambda#1]
Path parameters are not possible given the current parsing code..

// ParseFunction returns the fragment of path that occurs after
// the last '/' character, excluding query string and named anchors.

Instead of the 'last', I think you should use the first part of the path after the matching route.

For example.. using the config..

awslambda /api/ {

The path /api/dogs/rex should return the function name 'dogs' and not the name 'rex' ... this would enable path parameters to work properly.  Not sure the value of returning the last part of the path.

**Comment by coopernurse** [comment]
PR #1 has been rebased onto master, which should fix this issue.
