### ISSUE TITLE
Add awslambda to the new Caddy website

### ISSUE THREAD

**Issue by mholt** [coopernurse/caddy-awslambda#3]
Hey @coopernurse - I just wanted to reach out, I'm not sure if my email got through. There's a new Caddy website in staging that you should add the awslambda plugin to, so that people will be able to download and use it after April 20! People like it, someone just tweeted it the other day: https://twitter.com/pahudnet/status/850353283680026624

Let me know how to send you the link privately. :) The new website will allow you to manage your own releases and such, so it won't depend on me updating the build server manually, etc. I really want to get your plugin on the new site! :+1:

**Comment by coopernurse** [comment]
Hi Matt,

I've registered the plugin now.  Thanks for reaching out.
