### ISSUE TITLE
header_upstream directive

### ISSUE THREAD

**Issue by erdii** [coopernurse/caddy-awslambda#4]
Hi @coopernurse, neat plugin here!

It would be even neater if we could use the **header_upstream** directive in awslambda blocks, too!

Eg.: Currently there is no way to see the client ip inside a called lambda function. Something like:

```
header_upstream X-Real-IP {remote}
```

would solve this, I guess.

Or is there another way?

EDIT: I'm willing to offer my help with the implementation, but I'm only a "mediocre at best"-go-developer and need guidance 😀

**Comment by panva** [comment]
+1 to this, very much a welcome addition for caddy serving as a replacement for API gateway

**Comment by erdii** [comment]
It seems this repository is abandoned. Please have a look at my fork over here: https://github.com/erdii/caddy-awslambda

I also wrote bindings for aws-serverless-express here: https://github.com/erdii/caddy-serverless-express

**Comment by panva** [comment]
@erdii yeah, i might as well :) are you also experiencing #6?

> I also wrote bindings for aws-serverless-express here: erdii/caddy-serverless-express

I'm working on a generic one forked from https://github.com/dougmoscrop/serverless-http

**Comment by erdii** [comment]
@panva Not yet. But If you want I could try to have a look into it in the next days.

**Comment by coopernurse** [comment]
@erdii @panva - apologies for not being more active.  I'd be happy to give you both commit rights to this repo and we can fold in any commits from the fork.  Let me know!

**Comment by erdii** [comment]
Wohoo! I'd gladly take that offer! :)

**Comment by coopernurse** [comment]
@erdii Awesome! Done and done.  Thanks again.  Looks like we need to get the coveralls config tuned up.  It also looks like Caddy no longer builds with Go 1.8.  I can update travis.yml accordingly.

**Comment by erdii** [comment]
Nice!

Yeah that would be pretty neat!

How did you develop your plugin against caddy? Did you just full-compile caddy with the plugin each time you made a change or is there some easier way?

My iterations looked like this:
* Change code
* Commit and push to github (yes i know 😞)
* Compile caddy with the plugin url from github

And I'm pretty sure that you had something way easier.

**Comment by coopernurse** [comment]
Good question, I'm actually on a new computer now so I'm going to need to re-learn how to compile this locally.  My recollection is that you download the Caddy source and edit `run.go` to include an import for this plugin, then rebuild caddy.

See this doc: https://github.com/mholt/caddy/wiki/Plugging-in-Plugins-Yourself

**Comment by erdii** [comment]
Actually I wrote a tool for that: https://github.com/erdii/build-caddy
But I never found out if you could just use a relative path as a plugin url or if the code HAD to be built from a github repo.

**Comment by panva** [comment]
@coopernurse 

> I'd be happy to give you both commit rights to this repo

Not necessary for me, go isn't really my strong suit. Thank you!

**Comment by coopernurse** [comment]
@erdii - travis build is now fixed in master and README has been updated with notes on how to build caddy with this plugin enabled.  Should I just cherry-pick https://github.com/erdii/caddy-awslambda/commit/e3086b2c7cdf8986704b61a4049a4cf60cba88fd from your fork or should we merge your PR as it stands here?

**Comment by coopernurse** [comment]
@panva Sounds good.  Thanks for responding.  We'll see if we can get your bug figured out.

**Comment by erdii** [comment]
I'll just copy-paste the changes from my fork in a new branch, create a new pr for the tests and merge it if the tests run through.

**Comment by erdii** [comment]
implemented in #8
